---
- hosts: all
  vars:
    dokku_command: "{{ lookup('env','DOKKU_COMMAND') }}"
  tasks:
    - include: roles/common/tasks/ensure_intercity_hostfile.yml
    - include: roles/dokku/tasks/run_command.yml
    - debug: var=run_command_output.stdout_lines
